apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-and-mongodb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-and-mongodb
  template:
    metadata:
      labels:
        app: app-and-mongodb
    spec:
      containers:
      - name: nodejs-app
        image: pavaniguthula/student-db:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://localhost:27017/studentDB"
        - name: PORT
          value: "3000"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "studentDB"