version: '3.8'
services:
  nodejs:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/studentDB
    # If you need to mount code for live changes
    # volumes:
    #   - .:/usr/src/app
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
 
 