apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer # Use ClusterIP or NodePort based on your requirements
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: app-and-mongodb